server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:~/.h2/DBName;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true